In [1]:

import json
import pandas as pd
import numpy as np
import os
import glob
import re
from pathlib import Path

import datetime
from dateutil.relativedelta import relativedelta
from datetime import date
from collections import Counter

In [2]:
# Path to your data
path = "DATA"

# Get all .csv files at your path
allFiles = glob.glob(path + "/*.csv")

# Read in the data from files and safe to dictionary
dataStorage = {}
for filename in allFiles:
    name = os.path.basename(filename).split(".")[0]
    dataStorage[name] = pd.read_csv(filename)

In [3]:
# merge
out = pd.concat(dataStorage.values(), ignore_index=True)

In [4]:
out.count()

timestamp          45
trip_id            45
depart_airport     45
return_airport     45
depart_date        45
return_date        45
total_cost         45
depart_datetime    45
depart_duration    45
depart_stops       45
return_datetime    45
return_duration    45
return_stops       45
dtype: int64

In [5]:
out.dtypes

timestamp           object
trip_id             object
depart_airport      object
return_airport      object
depart_date         object
return_date         object
total_cost         float64
depart_datetime     object
depart_duration      int64
depart_stops         int64
return_datetime     object
return_duration      int64
return_stops         int64
dtype: object

In [6]:
 out["total_cost"]=out["total_cost"].astype(int)

In [7]:
path2 = "DATA/Output/mergedtest.csv"

In [8]:
out.to_csv(path2,index=False)

In [9]:
df = out
df.head()

,timestamp,trip_id,depart_airport,return_airport,depart_date,return_date,total_cost,depart_datetime,depart_duration,depart_stops,return_datetime,return_duration,return_stops
0,6/23/2022 3:41,SNA-SMF-06/23/2022-06/26/2022,SNA,SMF,6/23/2022,6/26/2022,720,6/23/2022 10:17,309,1,6/26/2022 6:00,341,1
1,6/23/2022 3:42,SNA-SMF-06/30/2022-07/03/2022,SNA,SMF,6/30/2022,7/3/2022,630,6/30/2022 10:17,309,1,6/30/2022 10:17,309,1
2,6/23/2022 3:43,SNA-PHX-06/23/2022-06/26/2022,SNA,PHX,6/23/2022,6/26/2022,353,6/23/2022 12:56,78,0,6/26/2022 10:13,88,0
3,6/23/2022 3:43,SNA-PHX-06/30/2022-07/03/2022,SNA,PHX,6/30/2022,7/3/2022,299,6/30/2022 12:56,78,0,7/3/2022 14:59,78,0
4,6/23/2022 3:44,SNA-ORD-06/23/2022-06/26/2022,SNA,ORD,6/23/2022,6/26/2022,2939,6/23/2022 16:44,636,1,6/26/2022 8:25,251,0

In [10]:
# df['day_before_purchase2'] = df.apply(lambda x : pd.Timedelta(x['depart_date']-x['timestamp']).days)

In [11]:
# Get Difference between purchase date and departure date
df['timestamp'] = pd.to_datetime(df['timestamp'])
df['depart_date'] = pd.to_datetime(df['depart_date'])
                        
# Create New Column 'day_before_purchase'                      
df['day_before_purchase'] = (df['depart_date'] - df['timestamp']).dt.days

In [12]:
df.dtypes

timestamp              datetime64[ns]
trip_id                        object
depart_airport                 object
return_airport                 object
depart_date            datetime64[ns]
return_date                    object
total_cost                      int32
depart_datetime                object
depart_duration                 int64
depart_stops                    int64
return_datetime                object
return_duration                 int64
return_stops                    int64
day_before_purchase             int64
dtype: object

In [13]:
df['day_before_purchase']

0     -1
1      6
2     -1
3      6
4     -1
5      6
6     -1
7      6
8     13
9     20
10    27
11    -1
12     6
13    13
14    20
15    27
16    -1
17     6
18    13
19    20
20    27
21    -1
22     6
23    13
24    20
25    27
26     5
27     5
28     5
29     5
30     5
31    12
32     5
33    12
34     5
35    12
36     5
37    12
38    12
39     5
40    12
41     5
42    12
43     5
44    12
Name: day_before_purchase, dtype: int64

In [14]:
num = df['day_before_purchase']._get_numeric_data()

In [15]:
num[num < 0] = 0

In [16]:
df['day_before_purchase']

0      0
1      6
2      0
3      6
4      0
5      6
6      0
7      6
8     13
9     20
10    27
11     0
12     6
13    13
14    20
15    27
16     0
17     6
18    13
19    20
20    27
21     0
22     6
23    13
24    20
25    27
26     5
27     5
28     5
29     5
30     5
31    12
32     5
33    12
34     5
35    12
36     5
37    12
38    12
39     5
40    12
41     5
42    12
43     5
44    12
Name: day_before_purchase, dtype: int64

In [17]:
# time_series = pd.Series(pd.timedelta_range(start='1 days', end='10 days', freq='1500T'))
# time_series.dt.components

In [18]:
path3 =  "tmintest.csv"

In [19]:
df2 = df
df2

,timestamp,trip_id,depart_airport,return_airport,depart_date,return_date,total_cost,depart_datetime,depart_duration,depart_stops,return_datetime,return_duration,return_stops,day_before_purchase
0,2022-06-23 03:41:00,SNA-SMF-06/23/2022-06/26/2022,SNA,SMF,2022-06-23,6/26/2022,720,6/23/2022 10:17,309,1,6/26/2022 6:00,341,1,0
1,2022-06-23 03:42:00,SNA-SMF-06/30/2022-07/03/2022,SNA,SMF,2022-06-30,7/3/2022,630,6/30/2022 10:17,309,1,6/30/2022 10:17,309,1,6
2,2022-06-23 03:43:00,SNA-PHX-06/23/2022-06/26/2022,SNA,PHX,2022-06-23,6/26/2022,353,6/23/2022 12:56,78,0,6/26/2022 10:13,88,0,0
3,2022-06-23 03:43:00,SNA-PHX-06/30/2022-07/03/2022,SNA,PHX,2022-06-30,7/3/2022,299,6/30/2022 12:56,78,0,7/3/2022 14:59,78,0,6
4,2022-06-23 03:44:00,SNA-ORD-06/23/2022-06/26/2022,SNA,ORD,2022-06-23,6/26/2022,2939,6/23/2022 16:44,636,1,6/26/2022 8:25,251,0,0
5,2022-06-23 03:45:00,SNA-ORD-06/30/2022-07/03/2022,SNA,ORD,2022-06-30,7/3/2022,582,6/30/2022 16:44,330,1,6/30/2022 16:44,330,1,6
6,2022-06-23 04:40:11,SNA-PHX-06/23/2022-06/27/2022,SNA,PHX,2022-06-23,06/27/2022,353,06-23-2022 12:56:00,78,0,06-27-2022 10:13:00,88,0,0
7,2022-06-23 04:41:02,SNA-PHX-06/30/2022-07/04/2022,SNA,PHX,2022-06-30,07/04/2022,269,06-30-2022 12:56:00,78,0,07-04-2022 10:18:00,88,0,6
8,2022-06-23 04:41:52,SNA-PHX-07/07/2022-07/11/2022,SNA,PHX,2022-07-07,07/11/2022,239,07-07-2022 13:11:00,79,0,07-11-2022 10:18:00,88,0,13
9,2022-06-23 04:42:43,SNA-PHX-07/14/2022-07/18/2022,SNA,PHX,2022-07-14,07/18/2022,300,07-14-2022 13:11:00,79,0,07-18-2022 14:00:00,79,0,20
10,2022-06-23 04:43:34,SNA-PHX-07/21/2022-07/25/2022,SNA,PHX,2022-07-21,07/25/2022,300,07-21-2022 16:44:00,84,0,07-25-2022 10:18:00,88,0,27
11,2022-06-23 04:44:30,SNA-ORD-06/23/2022-06/27/2022,SNA,ORD,2022-06-23,06/27/2022,2939,06-23-2022 16:44:00,636,1,06-27-2022 09:55:00,251,0,0
12,2022-06-23 04:45:25,SNA-ORD-06/30/2022-07/04/2022,SNA,ORD,2022-06-30,07/04/2022,582,06-30-2022 16:44:00,330,1,07-04-2022 11:52:00,486,1,6
13,2022-06-23 04:46:42,SNA-ORD-07/07/2022-07/11/2022,SNA,ORD,2022-07-07,07/11/2022,634,07-07-2022 10:17:00,330,1,07-11-2022 05:00:00,420,1,13
14,2022-06-23 04:47:37,SNA-ORD-07/14/2022-07/18/2022,SNA,ORD,2022-07-14,07/18/2022,690,07-14-2022 12:36:00,253,0,07-18-2022 05:00:00,387,1,20
15,2022-06-23 04:48:32,SNA-ORD-07/21/2022-07/25/2022,SNA,ORD,2022-07-21,07/25/2022,771,07-21-2022 16:44:00,330,1,07-25-2022 05:00:00,387,1,27
16,2022-06-23 04:49:31,LAX-PHX-06/23/2022-06/27/2022,LAX,PHX,2022-06-23,06/27/2022,273,06-23-2022 16:14:00,90,0,06-27-2022 16:40:00,83,0,0
17,2022-06-23 04:50:25,LAX-PHX-06/30/2022-07/04/2022,LAX,PHX,2022-06-30,07/04/2022,223,06-30-2022 12:21:00,90,0,07-04-2022 11:00:00,84,0,6
18,2022-06-23 04:51:19,LAX-PHX-07/07/2022-07/11/2022,LAX,PHX,2022-07-07,07/11/2022,183,07-07-2022 12:21:00,90,0,07-11-2022 13:46:00,84,0,13
19,2022-06-23 04:52:12,LAX-PHX-07/14/2022-07/18/2022,LAX,PHX,2022-07-14,07/18/2022,228,07-14-2022 16:14:00,90,0,07-18-2022 11:00:00,84,0,20
20,2022-06-23 04:53:06,LAX-PHX-07/21/2022-07/25/2022,LAX,PHX,2022-07-21,07/25/2022,198,07-21-2022 16:14:00,90,0,07-25-2022 13:46:00,84,0,27
21,2022-06-23 04:54:01,LAX-ORD-06/23/2022-06/27/2022,LAX,ORD,2022-06-23,06/27/2022,714,06-23-2022 10:55:00,404,1,06-27-2022 13:19:00,253,0,0
22,2022-06-23 04:54:55,LAX-ORD-06/30/2022-07/04/2022,LAX,ORD,2022-06-30,07/04/2022,579,06-30-2022 08:05:00,242,0,07-04-2022 15:20:00,252,0,6
23,2022-06-23 04:55:50,LAX-ORD-07/07/2022-07/11/2022,LAX,ORD,2022-07-07,07/11/2022,494,07-07-2022 08:00:00,385,1,07-11-2022 07:19:00,262,0,13
24,2022-06-23 04:56:48,LAX-ORD-07/14/2022-07/18/2022,LAX,ORD,2022-07-14,07/18/2022,588,07-14-2022 16:35:00,248,0,07-18-2022 06:45:00,450,1,20
25,2022-06-23 04:57:41,LAX-ORD-07/21/2022-07/25/2022,LAX,ORD,2022-07-21,07/25/2022,622,07-21-2022 17:50:00,248,0,07-25-2022 07:19:00,262,0,27
26,2022-06-24 01:29:01,SNA-PHX-06/30/2022-07/04/2022,SNA,PHX,2022-06-30,07/04/2022,280,06-30-2022 12:56:00,78,0,07-04-2022 10:18:00,88,0,5
27,2022-06-24 01:29:57,LAX-ORD-06/30/2022-07/04/2022,LAX,ORD,2022-06-30,07/04/2022,707,06-30-2022 10:10:00,255,0,07-04-2022 15:20:00,252,0,5
28,2022-06-24 01:30:59,SFO-IAD-06/30/2022-07/04/2022,SFO,IAD,2022-06-30,07/04/2022,1069,06-30-2022 07:05:00,310,0,07-04-2022 07:00:00,553,1,5
29,2022-06-24 01:31:56,SJC-MSY-06/30/2022-07/04/2022,SJC,MSY,2022-06-30,07/04/2022,1394,06-30-2022 12:37:00,484,2,07-04-2022 06:00:00,420,1,5
30,2022-06-24 01:48:17,SNA-PHX-06/30/2022-07/04/2022,SNA,PHX,2022-06-30,07/04/2022,280,06-30-2022 12:56:00,78,0,07-04-2022 14:00:00,79,0,5
31,2022-06-24 01:49:09,SNA-PHX-07/07/2022-07/11/2022,SNA,PHX,2022-07-07,07/11/2022,301,07-07-2022 13:11:00,79,0,07-11-2022 14:00:00,79,0,12
32,2022-06-24 01:50:04,LAX-ORD-06/30/2022-07/04/2022,LAX,ORD,2022-06-30,07/04/2022,707,06-30-2022 10:10:00,255,0,07-04-2022 15:20:00,252,0,5
33,2022-06-24 01:51:01,LAX-ORD-07/07/2022-07/11/2022,LAX,ORD,2022-07-07,07/11/2022,528,07-07-2022 17:50:00,248,0,07-11-2022 07:19:00,262,0,12
34,2022-06-24 01:52:03,SFO-IAD-06/30/2022-07/04/2022,SFO,IAD,2022-06-30,07/04/2022,1069,06-30-2022 07:05:00,310,0,07-04-2022 07:00:00,553,1,5
35,2022-06-24 01:52:57,SFO-IAD-07/07/2022-07/11/2022,SFO,IAD,2022-07-07,07/11/2022,958,07-07-2022 07:00:00,310,0,07-11-2022 16:10:00,355,0,12
36,2022-06-24 01:53:56,SJC-MSY-06/30/2022-07/04/2022,SJC,MSY,2022-06-30,07/04/2022,1262,06-30-2022 09:13:00,593,2,07-04-2022 06:00:00,420,1,5
37,2022-06-24 01:54:56,SJC-MSY-07/07/2022-07/11/2022,SJC,MSY,2022-07-07,07/11/2022,784,07-07-2022 06:10:00,537,1,07-11-2022 07:25:00,625,2,12
38,2022-06-25 00:00:00,SNA-PHX-07/07/2022-07/11/2022,SNA,PHX,2022-07-07,7/11/2022,301,7/7/2022,78,0,7/11/2022,79,0,12
39,2022-06-25 00:00:00,LAX-ORD-06/30/2022-07/04/2022,LAX,ORD,2022-06-30,7/4/2022,628,6/30/2022,255,0,7/4/2022,252,0,5
40,2022-06-25 00:00:00,LAX-ORD-07/07/2022-07/11/2022,LAX,ORD,2022-07-07,7/11/2022,571,7/7/2022,242,0,7/11/2022,262,0,12
41,2022-06-25 00:00:00,SFO-IAD-06/30/2022-07/04/2022,SFO,IAD,2022-06-30,7/4/2022,971,6/30/2022,310,0,7/4/2022,553,1,5
42,2022-06-25 00:00:00,SFO-IAD-07/07/2022-07/11/2022,SFO,IAD,2022-07-07,7/11/2022,908,7/7/2022,471,1,7/11/2022,486,1,12
43,2022-06-25 00:00:00,SJC-MSY-06/30/2022-07/04/2022,SJC,MSY,2022-06-30,7/4/2022,1470,6/30/2022,484,2,7/4/2022,420,1,5
44,2022-06-25 00:00:00,SJC-MSY-07/07/2022-07/11/2022,SJC,MSY,2022-07-07,7/11/2022,910,7/7/2022,414,1,7/11/2022,625,2,12

In [20]:
df2.dtypes

timestamp              datetime64[ns]
trip_id                        object
depart_airport                 object
return_airport                 object
depart_date            datetime64[ns]
return_date                    object
total_cost                      int32
depart_datetime                object
depart_duration                 int64
depart_stops                    int64
return_datetime                object
return_duration                 int64
return_stops                    int64
day_before_purchase             int64
dtype: object

In [21]:
# tmin = pd.to_timedelta(df2['day_before_purchase'])/pd.Timedelta('86400s')

In [22]:
df2.columns

Index(['timestamp', 'trip_id', 'depart_airport', 'return_airport',
       'depart_date', 'return_date', 'total_cost', 'depart_datetime',
       'depart_duration', 'depart_stops', 'return_datetime', 'return_duration',
       'return_stops', 'day_before_purchase'],
      dtype='object')

In [23]:
df2['total_min'] = num

In [24]:
df2

,timestamp,trip_id,depart_airport,return_airport,depart_date,return_date,total_cost,depart_datetime,depart_duration,depart_stops,return_datetime,return_duration,return_stops,day_before_purchase,total_min
0,2022-06-23 03:41:00,SNA-SMF-06/23/2022-06/26/2022,SNA,SMF,2022-06-23,6/26/2022,720,6/23/2022 10:17,309,1,6/26/2022 6:00,341,1,0,0
1,2022-06-23 03:42:00,SNA-SMF-06/30/2022-07/03/2022,SNA,SMF,2022-06-30,7/3/2022,630,6/30/2022 10:17,309,1,6/30/2022 10:17,309,1,6,6
2,2022-06-23 03:43:00,SNA-PHX-06/23/2022-06/26/2022,SNA,PHX,2022-06-23,6/26/2022,353,6/23/2022 12:56,78,0,6/26/2022 10:13,88,0,0,0
3,2022-06-23 03:43:00,SNA-PHX-06/30/2022-07/03/2022,SNA,PHX,2022-06-30,7/3/2022,299,6/30/2022 12:56,78,0,7/3/2022 14:59,78,0,6,6
4,2022-06-23 03:44:00,SNA-ORD-06/23/2022-06/26/2022,SNA,ORD,2022-06-23,6/26/2022,2939,6/23/2022 16:44,636,1,6/26/2022 8:25,251,0,0,0
5,2022-06-23 03:45:00,SNA-ORD-06/30/2022-07/03/2022,SNA,ORD,2022-06-30,7/3/2022,582,6/30/2022 16:44,330,1,6/30/2022 16:44,330,1,6,6
6,2022-06-23 04:40:11,SNA-PHX-06/23/2022-06/27/2022,SNA,PHX,2022-06-23,06/27/2022,353,06-23-2022 12:56:00,78,0,06-27-2022 10:13:00,88,0,0,0
7,2022-06-23 04:41:02,SNA-PHX-06/30/2022-07/04/2022,SNA,PHX,2022-06-30,07/04/2022,269,06-30-2022 12:56:00,78,0,07-04-2022 10:18:00,88,0,6,6
8,2022-06-23 04:41:52,SNA-PHX-07/07/2022-07/11/2022,SNA,PHX,2022-07-07,07/11/2022,239,07-07-2022 13:11:00,79,0,07-11-2022 10:18:00,88,0,13,13
9,2022-06-23 04:42:43,SNA-PHX-07/14/2022-07/18/2022,SNA,PHX,2022-07-14,07/18/2022,300,07-14-2022 13:11:00,79,0,07-18-2022 14:00:00,79,0,20,20
10,2022-06-23 04:43:34,SNA-PHX-07/21/2022-07/25/2022,SNA,PHX,2022-07-21,07/25/2022,300,07-21-2022 16:44:00,84,0,07-25-2022 10:18:00,88,0,27,27
11,2022-06-23 04:44:30,SNA-ORD-06/23/2022-06/27/2022,SNA,ORD,2022-06-23,06/27/2022,2939,06-23-2022 16:44:00,636,1,06-27-2022 09:55:00,251,0,0,0
12,2022-06-23 04:45:25,SNA-ORD-06/30/2022-07/04/2022,SNA,ORD,2022-06-30,07/04/2022,582,06-30-2022 16:44:00,330,1,07-04-2022 11:52:00,486,1,6,6
13,2022-06-23 04:46:42,SNA-ORD-07/07/2022-07/11/2022,SNA,ORD,2022-07-07,07/11/2022,634,07-07-2022 10:17:00,330,1,07-11-2022 05:00:00,420,1,13,13
14,2022-06-23 04:47:37,SNA-ORD-07/14/2022-07/18/2022,SNA,ORD,2022-07-14,07/18/2022,690,07-14-2022 12:36:00,253,0,07-18-2022 05:00:00,387,1,20,20
15,2022-06-23 04:48:32,SNA-ORD-07/21/2022-07/25/2022,SNA,ORD,2022-07-21,07/25/2022,771,07-21-2022 16:44:00,330,1,07-25-2022 05:00:00,387,1,27,27
16,2022-06-23 04:49:31,LAX-PHX-06/23/2022-06/27/2022,LAX,PHX,2022-06-23,06/27/2022,273,06-23-2022 16:14:00,90,0,06-27-2022 16:40:00,83,0,0,0
17,2022-06-23 04:50:25,LAX-PHX-06/30/2022-07/04/2022,LAX,PHX,2022-06-30,07/04/2022,223,06-30-2022 12:21:00,90,0,07-04-2022 11:00:00,84,0,6,6
18,2022-06-23 04:51:19,LAX-PHX-07/07/2022-07/11/2022,LAX,PHX,2022-07-07,07/11/2022,183,07-07-2022 12:21:00,90,0,07-11-2022 13:46:00,84,0,13,13
19,2022-06-23 04:52:12,LAX-PHX-07/14/2022-07/18/2022,LAX,PHX,2022-07-14,07/18/2022,228,07-14-2022 16:14:00,90,0,07-18-2022 11:00:00,84,0,20,20
20,2022-06-23 04:53:06,LAX-PHX-07/21/2022-07/25/2022,LAX,PHX,2022-07-21,07/25/2022,198,07-21-2022 16:14:00,90,0,07-25-2022 13:46:00,84,0,27,27
21,2022-06-23 04:54:01,LAX-ORD-06/23/2022-06/27/2022,LAX,ORD,2022-06-23,06/27/2022,714,06-23-2022 10:55:00,404,1,06-27-2022 13:19:00,253,0,0,0
22,2022-06-23 04:54:55,LAX-ORD-06/30/2022-07/04/2022,LAX,ORD,2022-06-30,07/04/2022,579,06-30-2022 08:05:00,242,0,07-04-2022 15:20:00,252,0,6,6
23,2022-06-23 04:55:50,LAX-ORD-07/07/2022-07/11/2022,LAX,ORD,2022-07-07,07/11/2022,494,07-07-2022 08:00:00,385,1,07-11-2022 07:19:00,262,0,13,13
24,2022-06-23 04:56:48,LAX-ORD-07/14/2022-07/18/2022,LAX,ORD,2022-07-14,07/18/2022,588,07-14-2022 16:35:00,248,0,07-18-2022 06:45:00,450,1,20,20
25,2022-06-23 04:57:41,LAX-ORD-07/21/2022-07/25/2022,LAX,ORD,2022-07-21,07/25/2022,622,07-21-2022 17:50:00,248,0,07-25-2022 07:19:00,262,0,27,27
26,2022-06-24 01:29:01,SNA-PHX-06/30/2022-07/04/2022,SNA,PHX,2022-06-30,07/04/2022,280,06-30-2022 12:56:00,78,0,07-04-2022 10:18:00,88,0,5,5
27,2022-06-24 01:29:57,LAX-ORD-06/30/2022-07/04/2022,LAX,ORD,2022-06-30,07/04/2022,707,06-30-2022 10:10:00,255,0,07-04-2022 15:20:00,252,0,5,5
28,2022-06-24 01:30:59,SFO-IAD-06/30/2022-07/04/2022,SFO,IAD,2022-06-30,07/04/2022,1069,06-30-2022 07:05:00,310,0,07-04-2022 07:00:00,553,1,5,5
29,2022-06-24 01:31:56,SJC-MSY-06/30/2022-07/04/2022,SJC,MSY,2022-06-30,07/04/2022,1394,06-30-2022 12:37:00,484,2,07-04-2022 06:00:00,420,1,5,5
30,2022-06-24 01:48:17,SNA-PHX-06/30/2022-07/04/2022,SNA,PHX,2022-06-30,07/04/2022,280,06-30-2022 12:56:00,78,0,07-04-2022 14:00:00,79,0,5,5
31,2022-06-24 01:49:09,SNA-PHX-07/07/2022-07/11/2022,SNA,PHX,2022-07-07,07/11/2022,301,07-07-2022 13:11:00,79,0,07-11-2022 14:00:00,79,0,12,12
32,2022-06-24 01:50:04,LAX-ORD-06/30/2022-07/04/2022,LAX,ORD,2022-06-30,07/04/2022,707,06-30-2022 10:10:00,255,0,07-04-2022 15:20:00,252,0,5,5
33,2022-06-24 01:51:01,LAX-ORD-07/07/2022-07/11/2022,LAX,ORD,2022-07-07,07/11/2022,528,07-07-2022 17:50:00,248,0,07-11-2022 07:19:00,262,0,12,12
34,2022-06-24 01:52:03,SFO-IAD-06/30/2022-07/04/2022,SFO,IAD,2022-06-30,07/04/2022,1069,06-30-2022 07:05:00,310,0,07-04-2022 07:00:00,553,1,5,5
35,2022-06-24 01:52:57,SFO-IAD-07/07/2022-07/11/2022,SFO,IAD,2022-07-07,07/11/2022,958,07-07-2022 07:00:00,310,0,07-11-2022 16:10:00,355,0,12,12
36,2022-06-24 01:53:56,SJC-MSY-06/30/2022-07/04/2022,SJC,MSY,2022-06-30,07/04/2022,1262,06-30-2022 09:13:00,593,2,07-04-2022 06:00:00,420,1,5,5
37,2022-06-24 01:54:56,SJC-MSY-07/07/2022-07/11/2022,SJC,MSY,2022-07-07,07/11/2022,784,07-07-2022 06:10:00,537,1,07-11-2022 07:25:00,625,2,12,12
38,2022-06-25 00:00:00,SNA-PHX-07/07/2022-07/11/2022,SNA,PHX,2022-07-07,7/11/2022,301,7/7/2022,78,0,7/11/2022,79,0,12,12
39,2022-06-25 00:00:00,LAX-ORD-06/30/2022-07/04/2022,LAX,ORD,2022-06-30,7/4/2022,628,6/30/2022,255,0,7/4/2022,252,0,5,5
40,2022-06-25 00:00:00,LAX-ORD-07/07/2022-07/11/2022,LAX,ORD,2022-07-07,7/11/2022,571,7/7/2022,242,0,7/11/2022,262,0,12,12
41,2022-06-25 00:00:00,SFO-IAD-06/30/2022-07/04/2022,SFO,IAD,2022-06-30,7/4/2022,971,6/30/2022,310,0,7/4/2022,553,1,5,5
42,2022-06-25 00:00:00,SFO-IAD-07/07/2022-07/11/2022,SFO,IAD,2022-07-07,7/11/2022,908,7/7/2022,471,1,7/11/2022,486,1,12,12
43,2022-06-25 00:00:00,SJC-MSY-06/30/2022-07/04/2022,SJC,MSY,2022-06-30,7/4/2022,1470,6/30/2022,484,2,7/4/2022,420,1,5,5
44,2022-06-25 00:00:00,SJC-MSY-07/07/2022-07/11/2022,SJC,MSY,2022-07-07,7/11/2022,910,7/7/2022,414,1,7/11/2022,625,2,12,12

In [25]:
df2.to_csv(path3,index=False)