In [1]:
import pandas as pd
import numpy as np
import datetime
import random
import time
from pathlib import Path

In [2]:
# Files to load
file_to_load = "merged.csv"

# Read the CSV into a DataFrame
df = pd.read_csv(file_to_load)
df

,timestamp,trip_id,depart_airport,return_airport,depart_date,return_date,total_cost,depart_datetime,depart_duration,depart_stops,return_datetime,return_duration,return_stops
0,6/23/2022,SNA-SMF-06/23/2022-06/26/2022,SNA,SMF,6/23/2022,6/26/2022,720,10:17:00 AM,309,1,6:00:00 AM,341,1
1,6/23/2022,SNA-SMF-06/30/2022-07/03/2022,SNA,SMF,6/30/2022,7/3/2022,630,10:17:00 AM,309,1,10:17:00 AM,309,1
2,6/23/2022,SNA-PHX-06/23/2022-06/26/2022,SNA,PHX,6/23/2022,6/26/2022,353,12:56:00 PM,78,0,10:13:00 AM,88,0
3,6/23/2022,SNA-PHX-06/30/2022-07/03/2022,SNA,PHX,6/30/2022,7/3/2022,299,12:56:00 PM,78,0,2:59:00 PM,78,0
4,6/23/2022,SNA-ORD-06/23/2022-06/26/2022,SNA,ORD,6/23/2022,6/26/2022,2939,4:44:00 PM,636,1,8:25:00 AM,251,0
5,6/23/2022,SNA-ORD-06/30/2022-07/03/2022,SNA,ORD,6/30/2022,7/3/2022,582,4:44:00 PM,330,1,4:44:00 PM,330,1
6,6/23/2022,SNA-PHX-06/23/2022-06/27/2022,SNA,PHX,6/23/2022,6/27/2022,353,12:56:00 PM,78,0,10:13:00 AM,88,0
7,6/23/2022,SNA-PHX-06/30/2022-07/04/2022,SNA,PHX,6/30/2022,7/4/2022,269,12:56:00 PM,78,0,10:18:00 AM,88,0
8,6/23/2022,SNA-PHX-07/07/2022-07/11/2022,SNA,PHX,7/7/2022,7/11/2022,239,1:11:00 PM,79,0,10:18:00 AM,88,0
9,6/23/2022,SNA-PHX-07/14/2022-07/18/2022,SNA,PHX,7/14/2022,7/18/2022,300,1:11:00 PM,79,0,2:00:00 PM,79,0
10,6/23/2022,SNA-PHX-07/21/2022-07/25/2022,SNA,PHX,7/21/2022,7/25/2022,300,4:44:00 PM,84,0,10:18:00 AM,88,0
11,6/23/2022,SNA-ORD-06/23/2022-06/27/2022,SNA,ORD,6/23/2022,6/27/2022,2939,4:44:00 PM,636,1,9:55:00 AM,251,0
12,6/23/2022,SNA-ORD-06/30/2022-07/04/2022,SNA,ORD,6/30/2022,7/4/2022,582,4:44:00 PM,330,1,11:52:00 AM,486,1
13,6/23/2022,SNA-ORD-07/07/2022-07/11/2022,SNA,ORD,7/7/2022,7/11/2022,634,10:17:00 AM,330,1,5:00:00 AM,420,1
14,6/23/2022,SNA-ORD-07/14/2022-07/18/2022,SNA,ORD,7/14/2022,7/18/2022,690,12:36:00 PM,253,0,5:00:00 AM,387,1
15,6/23/2022,SNA-ORD-07/21/2022-07/25/2022,SNA,ORD,7/21/2022,7/25/2022,771,4:44:00 PM,330,1,5:00:00 AM,387,1
16,6/23/2022,LAX-PHX-06/23/2022-06/27/2022,LAX,PHX,6/23/2022,6/27/2022,273,4:14:00 PM,90,0,4:40:00 PM,83,0
17,6/23/2022,LAX-PHX-06/30/2022-07/04/2022,LAX,PHX,6/30/2022,7/4/2022,223,12:21:00 PM,90,0,11:00:00 AM,84,0
18,6/23/2022,LAX-PHX-07/07/2022-07/11/2022,LAX,PHX,7/7/2022,7/11/2022,183,12:21:00 PM,90,0,1:46:00 PM,84,0
19,6/23/2022,LAX-PHX-07/14/2022-07/18/2022,LAX,PHX,7/14/2022,7/18/2022,228,4:14:00 PM,90,0,11:00:00 AM,84,0
20,6/23/2022,LAX-PHX-07/21/2022-07/25/2022,LAX,PHX,7/21/2022,7/25/2022,198,4:14:00 PM,90,0,1:46:00 PM,84,0
21,6/23/2022,LAX-ORD-06/23/2022-06/27/2022,LAX,ORD,6/23/2022,6/27/2022,714,10:55:00 AM,404,1,1:19:00 PM,253,0
22,6/23/2022,LAX-ORD-06/30/2022-07/04/2022,LAX,ORD,6/30/2022,7/4/2022,579,8:05:00 AM,242,0,3:20:00 PM,252,0
23,6/23/2022,LAX-ORD-07/07/2022-07/11/2022,LAX,ORD,7/7/2022,7/11/2022,494,8:00:00 AM,385,1,7:19:00 AM,262,0
24,6/23/2022,LAX-ORD-07/14/2022-07/18/2022,LAX,ORD,7/14/2022,7/18/2022,588,4:35:00 PM,248,0,6:45:00 AM,450,1
25,6/23/2022,LAX-ORD-07/21/2022-07/25/2022,LAX,ORD,7/21/2022,7/25/2022,622,5:50:00 PM,248,0,7:19:00 AM,262,0
26,6/24/2022,SNA-PHX-06/30/2022-07/04/2022,SNA,PHX,6/30/2022,7/4/2022,280,12:56:00 PM,78,0,10:18:00 AM,88,0
27,6/24/2022,LAX-ORD-06/30/2022-07/04/2022,LAX,ORD,6/30/2022,7/4/2022,707,10:10:00 AM,255,0,3:20:00 PM,252,0
28,6/24/2022,SFO-IAD-06/30/2022-07/04/2022,SFO,IAD,6/30/2022,7/4/2022,1069,7:05:00 AM,310,0,7:00:00 AM,553,1
29,6/24/2022,SJC-MSY-06/30/2022-07/04/2022,SJC,MSY,6/30/2022,7/4/2022,1394,12:37:00 PM,484,2,6:00:00 AM,420,1
30,6/24/2022,SNA-PHX-06/30/2022-07/04/2022,SNA,PHX,6/30/2022,7/4/2022,280,12:56:00 PM,78,0,2:00:00 PM,79,0
31,6/24/2022,SNA-PHX-07/07/2022-07/11/2022,SNA,PHX,7/7/2022,7/11/2022,301,1:11:00 PM,79,0,2:00:00 PM,79,0
32,6/24/2022,LAX-ORD-06/30/2022-07/04/2022,LAX,ORD,6/30/2022,7/4/2022,707,10:10:00 AM,255,0,3:20:00 PM,252,0
33,6/24/2022,LAX-ORD-07/07/2022-07/11/2022,LAX,ORD,7/7/2022,7/11/2022,528,5:50:00 PM,248,0,7:19:00 AM,262,0
34,6/24/2022,SFO-IAD-06/30/2022-07/04/2022,SFO,IAD,6/30/2022,7/4/2022,1069,7:05:00 AM,310,0,7:00:00 AM,553,1
35,6/24/2022,SFO-IAD-07/07/2022-07/11/2022,SFO,IAD,7/7/2022,7/11/2022,958,7:00:00 AM,310,0,4:10:00 PM,355,0
36,6/24/2022,SJC-MSY-06/30/2022-07/04/2022,SJC,MSY,6/30/2022,7/4/2022,1262,9:13:00 AM,593,2,6:00:00 AM,420,1
37,6/24/2022,SJC-MSY-07/07/2022-07/11/2022,SJC,MSY,7/7/2022,7/11/2022,784,6:10:00 AM,537,1,7:25:00 AM,625,2
38,6/25/2022,SNA-PHX-07/07/2022-07/11/2022,SNA,PHX,7/7/2022,7/11/2022,301,12:00:00 AM,78,0,12:00:00 AM,79,0
39,6/25/2022,LAX-ORD-06/30/2022-07/04/2022,LAX,ORD,6/30/2022,7/4/2022,628,12:00:00 AM,255,0,12:00:00 AM,252,0
40,6/25/2022,LAX-ORD-07/07/2022-07/11/2022,LAX,ORD,7/7/2022,7/11/2022,571,12:00:00 AM,242,0,12:00:00 AM,262,0
41,6/25/2022,SFO-IAD-06/30/2022-07/04/2022,SFO,IAD,6/30/2022,7/4/2022,971,12:00:00 AM,310,0,12:00:00 AM,553,1
42,6/25/2022,SFO-IAD-07/07/2022-07/11/2022,SFO,IAD,7/7/2022,7/11/2022,908,12:00:00 AM,471,1,12:00:00 AM,486,1
43,6/25/2022,SJC-MSY-06/30/2022-07/04/2022,SJC,MSY,6/30/2022,7/4/2022,1470,12:00:00 AM,484,2,12:00:00 AM,420,1
44,6/25/2022,SJC-MSY-07/07/2022-07/11/2022,SJC,MSY,7/7/2022,7/11/2022,910,12:00:00 AM,414,1,12:00:00 AM,625,2

In [3]:
df.count()

timestamp          45
trip_id            45
depart_airport     45
return_airport     45
depart_date        45
return_date        45
total_cost         45
depart_datetime    45
depart_duration    45
depart_stops       45
return_datetime    45
return_duration    45
return_stops       45
dtype: int64

In [4]:
df.head()

,timestamp,trip_id,depart_airport,return_airport,depart_date,return_date,total_cost,depart_datetime,depart_duration,depart_stops,return_datetime,return_duration,return_stops
0,6/23/2022,SNA-SMF-06/23/2022-06/26/2022,SNA,SMF,6/23/2022,6/26/2022,720,10:17:00 AM,309,1,6:00:00 AM,341,1
1,6/23/2022,SNA-SMF-06/30/2022-07/03/2022,SNA,SMF,6/30/2022,7/3/2022,630,10:17:00 AM,309,1,10:17:00 AM,309,1
2,6/23/2022,SNA-PHX-06/23/2022-06/26/2022,SNA,PHX,6/23/2022,6/26/2022,353,12:56:00 PM,78,0,10:13:00 AM,88,0
3,6/23/2022,SNA-PHX-06/30/2022-07/03/2022,SNA,PHX,6/30/2022,7/3/2022,299,12:56:00 PM,78,0,2:59:00 PM,78,0
4,6/23/2022,SNA-ORD-06/23/2022-06/26/2022,SNA,ORD,6/23/2022,6/26/2022,2939,4:44:00 PM,636,1,8:25:00 AM,251,0

In [5]:
df.isnull().sum()

timestamp          0
trip_id            0
depart_airport     0
return_airport     0
depart_date        0
return_date        0
total_cost         0
depart_datetime    0
depart_duration    0
depart_stops       0
return_datetime    0
return_duration    0
return_stops       0
dtype: int64

In [6]:
duplicateRows = df[df.duplicated(['trip_id'])]
duplicateRows

,timestamp,trip_id,depart_airport,return_airport,depart_date,return_date,total_cost,depart_datetime,depart_duration,depart_stops,return_datetime,return_duration,return_stops
26,6/24/2022,SNA-PHX-06/30/2022-07/04/2022,SNA,PHX,6/30/2022,7/4/2022,280,12:56:00 PM,78,0,10:18:00 AM,88,0
27,6/24/2022,LAX-ORD-06/30/2022-07/04/2022,LAX,ORD,6/30/2022,7/4/2022,707,10:10:00 AM,255,0,3:20:00 PM,252,0
30,6/24/2022,SNA-PHX-06/30/2022-07/04/2022,SNA,PHX,6/30/2022,7/4/2022,280,12:56:00 PM,78,0,2:00:00 PM,79,0
31,6/24/2022,SNA-PHX-07/07/2022-07/11/2022,SNA,PHX,7/7/2022,7/11/2022,301,1:11:00 PM,79,0,2:00:00 PM,79,0
32,6/24/2022,LAX-ORD-06/30/2022-07/04/2022,LAX,ORD,6/30/2022,7/4/2022,707,10:10:00 AM,255,0,3:20:00 PM,252,0
33,6/24/2022,LAX-ORD-07/07/2022-07/11/2022,LAX,ORD,7/7/2022,7/11/2022,528,5:50:00 PM,248,0,7:19:00 AM,262,0
34,6/24/2022,SFO-IAD-06/30/2022-07/04/2022,SFO,IAD,6/30/2022,7/4/2022,1069,7:05:00 AM,310,0,7:00:00 AM,553,1
36,6/24/2022,SJC-MSY-06/30/2022-07/04/2022,SJC,MSY,6/30/2022,7/4/2022,1262,9:13:00 AM,593,2,6:00:00 AM,420,1
38,6/25/2022,SNA-PHX-07/07/2022-07/11/2022,SNA,PHX,7/7/2022,7/11/2022,301,12:00:00 AM,78,0,12:00:00 AM,79,0
39,6/25/2022,LAX-ORD-06/30/2022-07/04/2022,LAX,ORD,6/30/2022,7/4/2022,628,12:00:00 AM,255,0,12:00:00 AM,252,0
40,6/25/2022,LAX-ORD-07/07/2022-07/11/2022,LAX,ORD,7/7/2022,7/11/2022,571,12:00:00 AM,242,0,12:00:00 AM,262,0
41,6/25/2022,SFO-IAD-06/30/2022-07/04/2022,SFO,IAD,6/30/2022,7/4/2022,971,12:00:00 AM,310,0,12:00:00 AM,553,1
42,6/25/2022,SFO-IAD-07/07/2022-07/11/2022,SFO,IAD,7/7/2022,7/11/2022,908,12:00:00 AM,471,1,12:00:00 AM,486,1
43,6/25/2022,SJC-MSY-06/30/2022-07/04/2022,SJC,MSY,6/30/2022,7/4/2022,1470,12:00:00 AM,484,2,12:00:00 AM,420,1
44,6/25/2022,SJC-MSY-07/07/2022-07/11/2022,SJC,MSY,7/7/2022,7/11/2022,910,12:00:00 AM,414,1,12:00:00 AM,625,2

In [7]:
df.dtypes

timestamp          object
trip_id            object
depart_airport     object
return_airport     object
depart_date        object
return_date        object
total_cost          int64
depart_datetime    object
depart_duration     int64
depart_stops        int64
return_datetime    object
return_duration     int64
return_stops        int64
dtype: object

In [8]:
df2 = df.drop_duplicates(subset='trip_id', keep='first', inplace=False, ignore_index=False)

In [9]:
# df.to_csv(index=False)

In [10]:
df2.to_csv(r'C:\Users\britt\Desktop\DATAFinal\'test.csv', index = False)